# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wapc < Formula
  desc "A simple description of your application."
  homepage "https://github.com/wapc/cli"
  version "0.0.4"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/wapc/cli/releases/download/v0.0.4/wapc_darwin_amd64.tar.gz"
    sha256 "8feeb6153d260bfab7a88aaa409a6a3dfe866c4549a25a6adbc3d187b027503a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wapc/cli/releases/download/v0.0.4/wapc_linux_amd64.tar.gz"
    sha256 "8a0c84bbf7e4395f0d282f66d2e12cc0231c424588dda29a546f1a6f0ee327da"
  end

  def install
    bin.install "wapc"
  end
end
