# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wapc < Formula
  desc "A simple description of your application."
  homepage "https://github.com/wapc/cli"
  version "0.0.1"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/wapc/cli/releases/download/v0.0.1/wapc_v0.0.1_darwin_amd64.tar.gz"
    sha256 "72ab3809cfc65ed618eec26f09f77518501ae21e6b7c256fd7666e1a63a64a07"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wapc/cli/releases/download/v0.0.1/wapc_v0.0.1_linux_amd64.tar.gz"
    sha256 "2865e194aa62ae9981dad830892de13248ba304c29c495b2051847e9cb63b275"
  end

  def install
    bin.install "wapc"
  end
end
